//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentElevate
{
    using System;
    using System.Collections.Generic;
    
    public partial class apply_tb
    {
        public int apply_id { get; set; }
        public int user_id { get; set; }
        public int job_id { get; set; }
        public string resume { get; set; }
        public System.DateTime date { get; set; }
        public string status { get; set; }
    
        public virtual jobs_tb jobs_tb { get; set; }
        public virtual user_reg_tb user_reg_tb { get; set; }
    }
}
