//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentElevate
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_reg_tb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public company_reg_tb()
        {
            this.jobs_tb = new HashSet<jobs_tb>();
        }
    
        public int company_id { get; set; }
        public string company_name { get; set; }
        public string company_email { get; set; }
        public string company_phone { get; set; }
        public string description { get; set; }
        public string website { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jobs_tb> jobs_tb { get; set; }
    }
}
